version: '3'

services:
  web:
    restart: always
    build: .
    env_file:
      - env/web.env
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:8.0
    env_file:
      - env/mysql.env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  nginx:
    restart: always
    image: nginx:1.17
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - web
    ports:
      - 8000:80

  mongodb:
    restart: always
    image: mongo:4.2
    env_file:
      - env/mongo.env
    volumes:
      - mongodb:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  mongodb:
    driver: local
